require("user.options")
require("user.keymaps")

require("config.lazy")

-- require("user.filetype")
require("user.icons")
require("user.colorscheme")
require("user.autocmds")
require("user.cmp")
require("user.lsp")
require("user.rustacean_nvim")
require("user.null_ls")
require("user.symbols_outline")
require("user.telescope")
require("user.statusline")
require("user.bufferline")
require("user.filetree")
require("user.treesitter")
-- require "user.indentline"
require("user.markdown")
require("user.toggleterm")
require("user.impatient")
require("user.alpha")
require("user.dap")
