require("core.options")
require("core.keymaps")

require("config.lazy")

-- require("user.filetype")
require("config.icons")
require("config.colorscheme")
require("core.autocmds")
require("user.cmp")
require("config.lsp")
require("user.rustacean_nvim")
require("user.null_ls")
require("user.outline")
-- require("user.telescope")
require("config.statusline")
require("config.bufferline")
require("config.filetree")
require("config.treesitter")
-- require "user.indentline"
require("config.markdown")
require("config.toggleterm")
-- require("user.impatient")
require("config.alpha")
require("user.dap")
